user : 
	python -m pip install -r requirements.txt
	python -m pip install .

dev : 
	python -m pip install -r requirements.txt
	python -m pip install -e .

clean :
	-rm -rf dvcs_xsx/saves/*
	-rm -rf dvcs_xsx/__pycache__
